#!/bin/sh
usage() {
	echo "usage: bump-version <version-id>"
}

if [ $# -ne 1 ]; then
	usage
	exit 1
fi

if ! sed 's/^GITFLOW_VERSION=.*$/GITFLOW_VERSION='$1'/g' git-tagflow-version > .git-tagflow-version.new; then
	echo "Could not replace GITFLOW_VERSION variable." >&2
	exit 2
fi

mv .git-tagflow-version.new git-tagflow-version
git add git-tagflow-version
git commit -m "Bumped version number to $1" git-tagflow-version
